global using Application.Libraries.Repositories;
global using Microsoft.Extensions.Configuration;
global using System.Data;
global using static Application.Models.ViewModels.BinViewModel;
global using static Application.Models.ViewModels.BinViewModel.BinMappingViewModel;
global using Application.Services.Core;
global using Application.Services.Repositories;
global using Microsoft.Extensions.DependencyInjection;
global using Application.Models.Registers;
global using DataManager.Services.Repositories;
global using AutoMapper;
global using DataManager.Models.Bins;
global using Application.Models.ViewModels;
global using DataManager.Models.QCMaintenance;
global using static Application.Models.ViewModels.QCMaintenanceViewModel;
global using Application.Libraries.DataAccess;
global using Newtonsoft.Json;
global using static Application.Models.ViewModels.ScheduleViewModel;
global using static Application.Models.ViewModels.FormsAndReportsViewModel;
global using static Application.Models.ViewModels.FormsAndReportsViewModel.IrradiationLabelPrintingViewModel;
global using static Application.Models.ViewModels.FormsAndReportsViewModel.IrradiationSalesOrderDetailsViewModel;
global using static Application.Models.ViewModels.FormsAndReportsViewModel.PalletLabelViewModel;
global using DataCipher;
global using DataManager.Models.Users;
global using static Application.Models.ViewModels.UserViewModel;
global using static Application.Models.ViewModels.QCOrderViewModel;
global using DataManager.Models.CertificateOfIrradiation;
global using DataManager.Models.QCOrder;
