// <auto-generated />
using System;
using DataManager.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataManager.Services.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231030135939_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataManager.Models.Bins.BinAssignment", b =>
                {
                    b.Property<string>("BinCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PalletNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SONo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BinCode");

                    b.ToTable("OBAS");
                });

            modelBuilder.Entity("DataManager.Models.Bins.BinMapping", b =>
                {
                    b.Property<string>("WarehouseCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseCode", "Shelf");

                    b.ToTable("OBMP");
                });

            modelBuilder.Entity("DataManager.Models.Bins.BinMappingPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aisle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Left")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<float>("Radius")
                        .HasColumnType("real");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Top")
                        .HasColumnType("real");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseCode", "Shelf");

                    b.ToTable("BPM1");
                });

            modelBuilder.Entity("DataManager.Models.Configurations.Modules", b =>
                {
                    b.Property<string>("ModuleId")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(254)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("IconGroup")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("IconSubGroup")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("LineNum")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("SubGroupName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("UpdatedUserId")
                        .HasColumnType("VARCHAR(32)");

                    b.Property<string>("WebLink")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("ModuleId");

                    b.ToTable("MODL");

                    b.HasData(
                        new
                        {
                            ModuleId = "USRL",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2767),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where you can create, update and delete user information.",
                            GroupName = "Administration",
                            Icon = "fa-id-card",
                            IconGroup = "fa-user-shield",
                            IconSubGroup = "fa-users",
                            LineNum = 0,
                            Name = "User Login Info",
                            SubGroupName = "User Management",
                            WebLink = "/USRL"
                        },
                        new
                        {
                            ModuleId = "USRA",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2770),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where you can create, update and delete user authorization.",
                            GroupName = "Administration",
                            Icon = "fa-unlock",
                            IconGroup = "fa-user-shield",
                            IconSubGroup = "fa-users",
                            LineNum = 1,
                            Name = "User Authorization",
                            SubGroupName = "User Management",
                            WebLink = "/USRA"
                        },
                        new
                        {
                            ModuleId = "USRG",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2772),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where you can create, update and delete user group.",
                            GroupName = "Administration",
                            Icon = "fa-list-ol",
                            IconGroup = "fa-user-shield",
                            IconSubGroup = "fa-users",
                            LineNum = 2,
                            Name = "User Group",
                            SubGroupName = "User Management",
                            WebLink = "/USRG"
                        },
                        new
                        {
                            ModuleId = "BNDB",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2774),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can see the Bin Map and Bin Status",
                            GroupName = "Dashboard",
                            Icon = "fa-map",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 3,
                            Name = "Bin Dashboard",
                            SubGroupName = "-",
                            WebLink = "/BinDashboard"
                        },
                        new
                        {
                            ModuleId = "QCMT",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2776),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can create Inspection Plans for specific items",
                            GroupName = "QC Maintenance",
                            Icon = "fa-magnifying-glass",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 4,
                            Name = "QC Maintenance",
                            SubGroupName = "-",
                            WebLink = "/QCMaintenance"
                        },
                        new
                        {
                            ModuleId = "BNMP",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2781),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can see map the bins",
                            GroupName = "Bins",
                            Icon = "fa-map",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 5,
                            Name = "Bin Mapping",
                            SubGroupName = "-",
                            WebLink = "/BinMapping"
                        },
                        new
                        {
                            ModuleId = "RSCD",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2783),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can view the Receiving Schedule",
                            GroupName = "Schedules",
                            Icon = "fa-truck",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 6,
                            Name = "Receiving Schedule",
                            SubGroupName = "-",
                            WebLink = "/ReceivingSchedule"
                        },
                        new
                        {
                            ModuleId = "DSCD",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2785),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can view the Dispatch Schedule",
                            GroupName = "Schedules",
                            Icon = "fa-box",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 7,
                            Name = "Dispatch Schedule",
                            SubGroupName = "-",
                            WebLink = "/DispatchSchedule"
                        },
                        new
                        {
                            ModuleId = "ISCD",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2787),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can view the Irradiation Schedule",
                            GroupName = "Schedules",
                            Icon = "fa-shield",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 8,
                            Name = "Irradiation Schedule",
                            SubGroupName = "-",
                            WebLink = "/IrradiationSchedule"
                        },
                        new
                        {
                            ModuleId = "QCOR",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2789),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can input QC Order details",
                            GroupName = "QC Order",
                            Icon = "fa-user-check",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 9,
                            Name = "QC Order",
                            SubGroupName = "-",
                            WebLink = "/QCOrder"
                        },
                        new
                        {
                            ModuleId = "BLPR",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2792),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can print bin labels",
                            GroupName = "Forms and Reports",
                            Icon = "fa-file-lines",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 10,
                            Name = "Bin Label Printing",
                            SubGroupName = "-",
                            WebLink = "/BinLabelPrinting"
                        },
                        new
                        {
                            ModuleId = "ILPR",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2794),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can print irradiation labels",
                            GroupName = "Forms and Reports",
                            Icon = "fa-file-lines",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 11,
                            Name = "Irradiation Label Printing",
                            SubGroupName = "-",
                            WebLink = "/IrradiationLabelPrinting"
                        },
                        new
                        {
                            ModuleId = "PLPR",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2796),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can print pallet labels",
                            GroupName = "Forms and Reports",
                            Icon = "fa-file-lines",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 12,
                            Name = "Pallet Label Printing",
                            SubGroupName = "-",
                            WebLink = "/PalletLabelPrinting"
                        },
                        new
                        {
                            ModuleId = "RCVN",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2798),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can receive sales orders",
                            GroupName = "Receiving",
                            Icon = "fa-truck-ramp-box",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 13,
                            Name = "Receiving",
                            SubGroupName = "-",
                            WebLink = "/Receiving"
                        },
                        new
                        {
                            ModuleId = "INVT",
                            Active = false,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2800),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Description = "This is where user can execute inventory transfer",
                            GroupName = "Inventory Transfer",
                            Icon = "fa-dolly",
                            IconGroup = "-",
                            IconSubGroup = "-",
                            LineNum = 14,
                            Name = "Inventory Transfer",
                            SubGroupName = "-",
                            WebLink = "/InventoryTransfer"
                        });
                });

            modelBuilder.Entity("DataManager.Models.QCMaintenance.InspectionPlan", b =>
                {
                    b.Property<string>("InspectionPlanCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosimeterLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionPlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfSamples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfDosimeters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallPassTolerancePercentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SamplePassTolerancePercentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalNumberOfBoxes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalWeight")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InspectionPlanCode", "Version");

                    b.ToTable("QCIP");
                });

            modelBuilder.Entity("DataManager.Models.QCMaintenance.InspectionPlanParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("InspectionPlanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaxValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("InspectionPlanCode", "Version");

                    b.ToTable("CIP1");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrder", b =>
                {
                    b.Property<string>("QCOrderNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocNo")
                        .HasColumnType("int");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionPlanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionPlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionPlanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturingLotNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OverallPassTolerancePercentage")
                        .HasColumnType("real");

                    b.Property<string>("PONo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SamplePassTolerancePercentage")
                        .HasColumnType("real");

                    b.Property<int>("SampleSize")
                        .HasColumnType("int");

                    b.Property<string>("ServiceOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QCOrderNo");

                    b.ToTable("QCOR");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderDosimetryReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualEnergy")
                        .HasColumnType("int");

                    b.Property<int>("ActualFrequency")
                        .HasColumnType("int");

                    b.Property<int>("ActualPower")
                        .HasColumnType("int");

                    b.Property<string>("EBOperationLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NCReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QCOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalProductsAfterIrradiation")
                        .HasColumnType("int");

                    b.Property<int>("TotalProductsBeforeIrradiation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QCOrderNo")
                        .IsUnique();

                    b.ToTable("COR4");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderParameterList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterNo")
                        .HasColumnType("int");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.ToTable("COR3");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderSampleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Open")
                        .HasColumnType("int");

                    b.Property<string>("QCOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalNoOfFailed")
                        .HasColumnType("int");

                    b.Property<int>("TotalNoOfPassed")
                        .HasColumnType("int");

                    b.Property<int>("TotalNoSamples")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QCOrderNo")
                        .IsUnique();

                    b.ToTable("COR1");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderSampleList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfFailed")
                        .HasColumnType("int");

                    b.Property<int>("NoOfPassed")
                        .HasColumnType("int");

                    b.Property<string>("QABy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.Property<int>("SampleNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.ToTable("COR2");
                });

            modelBuilder.Entity("DataManager.Models.Users.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("Background")
                        .HasColumnType("tinyint");

                    b.Property<string>("Company")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.Property<string>("Department")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<byte?>("DisplayPicture")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("UpdatedUserId")
                        .HasColumnType("VARCHAR(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("USRD");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Direc Business Technologies Inc",
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2453),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            Department = "Administration",
                            Email = "admin@gmail.com",
                            FirstName = "Direc",
                            IsActive = true,
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            LastName = "Admin",
                            MiddleName = "",
                            UserId = "9f7e920b817349cf870706724d71a739"
                        });
                });

            modelBuilder.Entity("DataManager.Models.Users.UserGroups", b =>
                {
                    b.Property<int>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("UpdatedUserId")
                        .HasColumnType("VARCHAR(32)");

                    b.HasKey("UserGroupId");

                    b.ToTable("USRG");

                    b.HasData(
                        new
                        {
                            UserGroupId = 1,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2570),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            GroupName = "Unset",
                            IsActive = true
                        },
                        new
                        {
                            UserGroupId = 2,
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2572),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            GroupName = "Administrator",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DataManager.Models.Users.UserLogins", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR(32)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.Property<DateTime?>("FailedAttempt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedoutEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("LastPassword")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("LastPasswordSet")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("ResetAttempt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("UpdatedUserId")
                        .HasColumnType("VARCHAR(32)");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("UserId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("USRL");

                    b.HasData(
                        new
                        {
                            UserId = "9f7e920b817349cf870706724d71a739",
                            CreatedDate = new DateTime(2023, 10, 30, 13, 59, 39, 497, DateTimeKind.Utc).AddTicks(2444),
                            CreatedUserId = "9f7e920b817349cf870706724d71a739",
                            FailedAttemptCount = 0,
                            IsActive = true,
                            IsLocked = true,
                            IsLockedoutEnabled = true,
                            IsSuperUser = true,
                            IsTwoFactorEnabled = true,
                            Password = "Uxz7RIWltZj6xFSwsSx775FGJK6qcRCCA0z+dt8CcyNxsmS7N7Rmp0bn0S0mxjiS",
                            UserGroupId = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DataManager.Models.Users.UserModules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("UpdatedUserId")
                        .HasColumnType("VARCHAR(32)");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("USRM");
                });

            modelBuilder.Entity("DataManager.Models.Bins.BinMappingPin", b =>
                {
                    b.HasOne("DataManager.Models.Bins.BinMapping", "BinMapping")
                        .WithMany("BinMappingPins")
                        .HasForeignKey("WarehouseCode", "Shelf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinMapping");
                });

            modelBuilder.Entity("DataManager.Models.QCMaintenance.InspectionPlanParameter", b =>
                {
                    b.HasOne("DataManager.Models.QCMaintenance.InspectionPlan", "InspectionPlan")
                        .WithMany("ParameterList")
                        .HasForeignKey("InspectionPlanCode", "Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectionPlan");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderDosimetryReport", b =>
                {
                    b.HasOne("DataManager.Models.QCOrder.QCOrder", "QCOrder")
                        .WithOne("QCOrderDosimetryReport")
                        .HasForeignKey("DataManager.Models.QCOrder.QCOrderDosimetryReport", "QCOrderNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QCOrder");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderParameterList", b =>
                {
                    b.HasOne("DataManager.Models.QCOrder.QCOrderSampleList", "QCOrderSampleList")
                        .WithMany("QCOrderParameterList")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QCOrderSampleList");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderSampleDetail", b =>
                {
                    b.HasOne("DataManager.Models.QCOrder.QCOrder", "QCOrder")
                        .WithOne("QCOrderSampleDetail")
                        .HasForeignKey("DataManager.Models.QCOrder.QCOrderSampleDetail", "QCOrderNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QCOrder");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderSampleList", b =>
                {
                    b.HasOne("DataManager.Models.QCOrder.QCOrderSampleDetail", "QCOrderSampleDetail")
                        .WithMany("QCOrderSampleList")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QCOrderSampleDetail");
                });

            modelBuilder.Entity("DataManager.Models.Users.UserDetails", b =>
                {
                    b.HasOne("DataManager.Models.Users.UserLogins", "UserLogins")
                        .WithOne("UserDetails")
                        .HasForeignKey("DataManager.Models.Users.UserDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserLogins");
                });

            modelBuilder.Entity("DataManager.Models.Users.UserLogins", b =>
                {
                    b.HasOne("DataManager.Models.Users.UserGroups", "UserGroup")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("DataManager.Models.Users.UserModules", b =>
                {
                    b.HasOne("DataManager.Models.Configurations.Modules", "Modules")
                        .WithMany("UserModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManager.Models.Users.UserGroups", "UserGroups")
                        .WithMany("UserModules")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modules");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("DataManager.Models.Bins.BinMapping", b =>
                {
                    b.Navigation("BinMappingPins");
                });

            modelBuilder.Entity("DataManager.Models.Configurations.Modules", b =>
                {
                    b.Navigation("UserModules");
                });

            modelBuilder.Entity("DataManager.Models.QCMaintenance.InspectionPlan", b =>
                {
                    b.Navigation("ParameterList");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrder", b =>
                {
                    b.Navigation("QCOrderDosimetryReport")
                        .IsRequired();

                    b.Navigation("QCOrderSampleDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderSampleDetail", b =>
                {
                    b.Navigation("QCOrderSampleList");
                });

            modelBuilder.Entity("DataManager.Models.QCOrder.QCOrderSampleList", b =>
                {
                    b.Navigation("QCOrderParameterList");
                });

            modelBuilder.Entity("DataManager.Models.Users.UserGroups", b =>
                {
                    b.Navigation("UserLogins");

                    b.Navigation("UserModules");
                });

            modelBuilder.Entity("DataManager.Models.Users.UserLogins", b =>
                {
                    b.Navigation("UserDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
